name: pypi

# 任务触发
on:
  # 当 提交到当前仓库时立即运行
  push:
    tags:
      - 'v*'

jobs:
  linux-build:
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        py_version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.py_version }}
           architecture: "x64"
      
      - name: "Which python"
        run: "which python && which pip"

      - name: "Setup build"
        run: "pip install build"

      - name: "Install zlib"
        run : "sudo apt install zlib1g-dev -y"

      - name: "Build diamond4py"
        run: "python -m build"

      - name: "Test install"
        run: pip install dist/diamond4py*whl && python -c "import diamond4py"

      - uses: actions/upload-artifact@v3
        with:
          name: build_package
          path: dist/*

  release:
    needs: ["linux-build"]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build_package
          path: dist/

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          draft: true

      - name: Relase to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ vars.PYPI_URL }}
          packages_dir: dist/
