name: pypi

# 任务触发
on:
  # 当 提交到当前仓库时立即运行
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        py_version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.py_version }}
           architecture: "x64"
      
      - name: "Which python"
        run: "which python && which pip"

      - name: "Setup build"
        run: "pip install build auditwheel==5.0.0"

      - name: "Install zlib"
        run : "sudo apt install zlib1g-dev -y"

      - name: "Build diamond4py"
        run: "python -m build"

      - name: "Test install"
        run: pip install dist/diamond4py*whl
        
      - name: "Test case"
        run: pushd test; python test.py; popd

      - name: "Repair manylinux"
        run: |
          auditwheel show dist/*-linux*whl && 
          auditwheel repair dist/*-linux*whl --plat manylinux_2_27_x86_64 -w dist &&
          rm dist/*-linux*whl

      - name: Get version
        id: version
        uses: frabert/replace-string-action@v2
        with:
          pattern: 'refs/tags/v(.+)'
          string: ${{ github.ref }}
          replace-with: 'v$1'

      - uses: actions/upload-artifact@v3
        with:
          name: build_${{ steps.version.outputs.replaced }}
          path: dist/*
          retention-days: 1

  release:
    needs: ["linux-build"]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: frabert/replace-string-action@v2
        with:
          pattern: 'refs/tags/v(.+)'
          string: ${{ github.ref }}
          replace-with: 'v$1'

      - uses: actions/download-artifact@v3
        with:
          name: build_${{ steps.version.outputs.replaced }}
          path: dist/

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          draft: true

      - name: Relase to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ vars.PYPI_URL }}
          packages_dir: dist/
